# 5.)

x prints 3 in the first program and gives an error in the second program.  This is because in the first program x is defined outside of the inner scope.  However, in the second code example the error message originates from the fact that outer scope cannot access variables originating in inner scope.  